# Generated by Django 5.2.8 on 2025-12-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
