# Generated by Django 5.2.8 on 2025-12-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
